### ISSUE TITLE
[Insight] Absolute path constants __DIR__ and __FILE__ should not be used - in …/EntityResolverCompilerPass.php, line 19

### ISSUE THREAD

**Issue by nicolasThal** [open-orchestra/open-orchestra-user-bundle#54]
**[in UserBundle/DependencyInjection/Compiler/EntityResolverCompilerPass.php, line 19](https://github.com/open-orchestra/open-orchestra-user-bundle/blob/22c60063fc3ba0bc49b1381dd129410d5b9768ac/UserBundle/DependencyInjection/Compiler/EntityResolverCompilerPass.php#L19)**

> `__DIR__` and `__FILE__` constants may conflict with the Symfony resource overriding system

```php
    /**
     * @param ContainerBuilder $container
     */
    public function process(ContainerBuilder $container)
    {
        $defaultResolveDocument = Yaml::parse(file_get_contents(__DIR__.'/../../Resources/config/resolve_document.yml'))['resolve_target_documents'];

        $definition = $container->findDefinition('doctrine_mongodb.odm.listeners.resolve_target_document');
        $definitionCalls = $definition->getMethodCalls();
        foreach($defaultResolveDocument as $interface => $class) {
            if (! $this->resolverExist($definitionCalls, $interface)) {
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/7e9bf4b8-87e9-4572-a1e1-a67880a1d5af/analyses/1)_

**Comment by itkg-alavieille** [comment]
this commit https://github.com/open-orchestra/open-orchestra-user-bundle/commit/9ab10011629fdff51d3dd5aa0eb5627cf6231439 fix this.
